name: Run channels

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
  push:

jobs:
  channel-one:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install APT Dependancies
        run: sudo apt update && sudo apt install git bash python3 python3-pip sshpass -y

      - name: Install Python Depdenancies
        run: pip install -r requirements.txt

      - name: Run application
        run: python3 main.py
        env:
          TOGGL_API_TOKEN: "${{ fromJSON(secrets.CHANNEL_1).test }}"