name: Run channels

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
  push:

jobs:
  channel-one:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install APT Dependancies
        run: sudo apt update && sudo apt install git bash python3 python3-pip sshpass -y

      - name: Install Python Depdenancies
        run: pip install -r requirements.txt

      - name: Run application
        run: python3 main.py
        env:
          TOGGL_API_TOKEN: "${{ fromJSON(secrets.CHANNEL_1).TOGGL_API_TOKEN }}"
          CONFLUENCE_URL: "${{ fromJSON(secrets.CHANNEL_1).CONFLUENCE_URL }}"
          CONFLUENCE_USERNAME: "${{ fromJSON(secrets.CHANNEL_1).CONFLUENCE_USERNAME }}"
          CONFLUENCE_API_TOKEN: "${{ fromJSON(secrets.CHANNEL_1).CONFLUENCE_API_TOKEN }}"
          CONFLUENCE_SPACE_KEY: "${{ fromJSON(secrets.CHANNEL_1).CONFLUENCE_SPACE_KEY }}"
          CONFLUENCE_PARENT_PAGE_ID: "${{ fromJSON(secrets.CHANNEL_1).CONFLUENCE_PARENT_PAGE_ID }}"
          PROJECT_ID: "${{ fromJSON(secrets.CHANNEL_1).PROJECT_ID }}"
          WORKSPACE_ID: "${{ fromJSON(secrets.CHANNEL_1).WORKSPACE_ID }}"